import {
  _1977,
  Aden,
  Brannan,
  Brooklyn,
  Clarendon,
  Earlybird,
  Gingham,
  Hudson,
  Inkwell,
  Kelvin,
  Lark,
  Lofi,
  Maven,
  Mayfair,
  Moon,
  Nashville,
  Perpetua,
  Reyes,
  Rise,
  Slumber,
  Stinson,
  Toaster,
  Valencia,
  Walden,
  Willow,
  Xpro2
} from 'react-native-image-filter-kit'

const LIST_COMPONENTS = [
  null,
  _1977,
  Aden,
  Brannan,
  Brooklyn,
  Clarendon,
  Earlybird,
  Gingham,
  Hudson,
  Inkwell,
  Kelvin,
  Lark,
  Lofi,
  Maven,
  Mayfair,
  Moon,
  Nashville,
  Perpetua,
  Reyes,
  Rise,
  Slumber,
  Stinson,
  Toaster,
  Valencia,
  Walden,
  Willow,
  Xpro2
]

const EFFECT_OPTIONS = [
  { id: 1, filter: 'Normal' },
  { id: 2, filter: '_1977' },
  { id: 3, filter: 'Aden' },
  { id: 4, filter: 'Brannan' },
  { id: 5, filter: 'Brooklyn' },
  { id: 6, filter: 'Clarendon' },
  { id: 7, filter: 'Earlybird' },
  { id: 8, filter: 'Gingham' },
  { id: 9, filter: 'Hudson' },
  { id: 10, filter: 'Inkwell' },
  { id: 11, filter: 'Kelvin' },
  { id: 12, filter: 'Lark' },
  { id: 13, filter: 'Lofi' },
  { id: 14, filter: 'Maven' },
  { id: 15, filter: 'Mayfair' },
  { id: 16, filter: 'Moon' },
  { id: 17, filter: 'Nashville' },
  { id: 18, filter: 'Perpetua' },
  { id: 19, filter: 'Reyes' },
  { id: 20, filter: 'Slumber' },
  { id: 21, filter: 'Stinson' },
  { id: 22, filter: 'Toaster' },
  { id: 23, filter: 'Valencia' },
  { id: 24, filter: 'Willow' },
  { id: 25, filter: 'Xpro2' }
]

export {
  EFFECT_OPTIONS,
  LIST_COMPONENTS
}
